module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  fontawesome_iconpicker_widget: 0
  fontawesome_media: 0
  fontawesome_menu_icons: 0
  help: 0
  history: 0
  image: 0
  language: 0
  link: 0
  media: 0
  media_library: 0
  menu_item_extras: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_manipulator: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  svg_image: 0
  svg_image_responsive: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  tb_megamenu: 0
  text: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_infinite_scroll: 0
  views_show_more: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_devel: 0
  webform_image_select: 0
  webform_node: 0
  webform_options_custom: 0
  webform_options_limit: 0
  webform_scheduled_email: 0
  webform_share: 0
  webform_shortcuts: 0
  webform_submission_export_import: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  webform_bootstrap: 1
  views: 10
  standard: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  classy: 0
  shopspot: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
