scrollup_position: '1'
scrollup_button_bg_color: '#e51515'
scrollup_button_hover_bg_color: '#3a07b0'
scrollup_title: ''
scrollup_window_position: '600'
scrollup_speed: '100'
scrollup_themename:
  shopspot: shopspot
